FROM node:20 AS builder

WORKDIR /app
COPY package.json ./
COPY yarn.lock ./

RUN yarn

COPY . .

ENV NODE_ENV=production
RUN yarn build

FROM nginx:alpine3.20

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80